import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import Ribbon from "@/components/Ribbon/Ribbon";
import SearchBox from "@/components/SearchBox/SearchBox";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/Footer/Footer";

export const metadata = {
  title: {
    default: "Movie Store",
    template: "%s | Movie Store",
  },
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <ToastContainer position="top-right" autoClose="2000" />
        <Ribbon />
        <SearchBox />
        {children}
        <Footer />
      </body>
    </html>
  );
}
