import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import Ribbon from "@/components/Ribbon/Ribbon";
import SearchBox from "@/components/SearchBox/SearchBox";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/Footer/Footer";
import { ThemeProvider } from "@/context/ThemeContext";
import { Analytics } from "@vercel/analytics/next";

export const metadata = {
  title: {
    default: "Movie Store",
    template: "%s | Movie Store",
  },
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Navbar />
          <ToastContainer position="top-right" autoClose="2000" />
          <Ribbon />
          <SearchBox />
          {children}
          <Analytics />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
